version: '3.3'
# version: "2.2"
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'syarah'   
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1

  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: yii2logs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mysql-data:
  mongodbdata:
    driver: local

# curl -XPOST cpost-elastics/_delete_by_query?conflicts=proceed -d '{"query": {"match_all": {}}}'